CREATE SCHEMA mstar;

CREATE TYPE mstar."statement_period" AS ENUM (
  'Year',
  'Quarter');

CREATE TABLE mstar.balance_sheet_assets (
  act_symbol text NOT NULL,
  "date" date NOT NULL,
  "period" mstar."statement_period" NOT NULL,
  currency text NOT NULL,
  cash_and_equivalents numeric NULL,
  short_term_investments numeric NULL,
  cash_and_equivalents_and_short_term_investments numeric NULL,
  restricted_cash_current numeric NULL,
  inventories numeric NULL,
  accounts_receivable_current numeric NULL,
  other_receivables_current numeric NULL,
  trade_and_other_receivables_current numeric NULL,
  deferred_tax_current numeric NULL,
  deferred_costs_current numeric NULL,
  assets_held_for_sale_current numeric NULL,
  derivatives_investments_current numeric NULL,
  regulatory_assets_current numeric NULL,
  prepayments_and_deposits_current numeric NULL,
  other_current_assets numeric NULL,
  total_current_assets numeric NULL,
  net_property_plant_and_equipment numeric NULL,
  intangibles numeric NULL,
  trade_and_other_receivables_non_current numeric NULL,
  prepayments_and_deposits_non_current numeric NULL,
  deferred_tax_non_current numeric NULL,
  deferred_costs_non_current numeric NULL,
  pension_non_current numeric NULL,
  long_term_investments numeric NULL,
  assets_held_for_sale_non_current numeric NULL,
  inventories_non_current numeric NULL,
  mineral_property_interests numeric NULL,
  regulatory_assets_non_current numeric NULL,
  investment_properties numeric NULL,
  biological_assets numeric NULL,
  restricted_cash_non_current numeric NULL,
  derivatives_investments_non_current numeric NULL,
  other_non_current_assets numeric NULL,
  total_non_current_assets numeric NULL,
  total_assets numeric NULL,
  CONSTRAINT balance_sheet_assets_pkey PRIMARY KEY (act_symbol, date, period),
  CONSTRAINT balance_sheet_assets_act_symbol_fkey FOREIGN KEY (act_symbol) REFERENCES nasdaq.symbol(act_symbol)
);

CREATE TABLE mstar.balance_sheet_equity (
  act_symbol text NOT NULL,
  "date" date NOT NULL,
  "period" mstar."statement_period" NOT NULL,
  currency text NOT NULL,
  preferred_stock numeric NULL,
  common_stock numeric NULL,
  additional_paid_in_capital numeric NULL,
  capital_stock numeric NULL,
  treasury_stock numeric NULL,
  paid_in_capital numeric NULL,
  stock_options_warrants_deferred_shares_convertible_debentures numeric NULL,
  retained_earnings numeric NULL,
  reserves numeric NULL,
  stock_subscription numeric NULL,
  perpetual_capital_securities_holder_equity numeric NULL,
  other_equity_interest numeric NULL,
  total_parent_stockholder_equity numeric NULL,
  minority_interest_in_equity numeric NULL,
  total_partnership_capital numeric NULL,
  total_equity numeric NULL,
  CONSTRAINT balance_sheet_equity_pkey PRIMARY KEY (act_symbol, date, period),
  CONSTRAINT balance_sheet_equity_act_symbol_fkey FOREIGN KEY (act_symbol) REFERENCES nasdaq.symbol(act_symbol)
);

CREATE TABLE mstar.balance_sheet_liabilities (
  act_symbol text NOT NULL,
  "date" date NOT NULL,
  "period" mstar."statement_period" NOT NULL,
  currency text NOT NULL,
  accounts_payable_current numeric NULL,
  taxes_payable_current numeric NULL,
  trade_and_other_payables_current numeric NULL,
  accrued_expenses_current numeric NULL,
  payables_and_accrued_expenses_current numeric NULL,
  current_portion_long_term_debt numeric NULL,
  capital_lease_obligations_current numeric NULL,
  current_debt numeric NULL,
  current_debt_and_capital_lease_obligation numeric NULL,
  financial_liabilities_current numeric NULL,
  provisions_current numeric NULL,
  deferred_liabilities_current numeric NULL,
  discontinued_operations_liabilities_current numeric NULL,
  regulatory_liabilities_current numeric NULL,
  tax_liabilities_current numeric NULL,
  other_current_liabilities numeric NULL,
  total_current_liabilities numeric NULL,
  long_term_debt numeric NULL,
  financial_liabilities_non_current numeric NULL,
  provisions_non_current numeric NULL,
  deferred_tax_liabilities_non_current numeric NULL,
  tax_liabilities_non_current numeric NULL,
  deferred_income_non_current numeric NULL,
  deferred_liabilities_non_current numeric NULL,
  payables_and_accrued_expenses_non_current numeric NULL,
  preferred_securities_outside_stock_equity numeric NULL,
  restricted_common_stock numeric NULL,
  liabilities_held_for_sale_non_current numeric NULL,
  regulatory_liabilities_non_current numeric NULL,
  other_non_current_liabilities numeric NULL,
  total_non_current_liabilities numeric NULL,
  total_liabilities numeric NULL,
  CONSTRAINT balance_sheet_liabilities_pkey PRIMARY KEY (act_symbol, date, period),
  CONSTRAINT balance_sheet_liabilities_act_symbol_fkey FOREIGN KEY (act_symbol) REFERENCES nasdaq.symbol(act_symbol)
);

CREATE TABLE mstar.cash_flow_statement (
  act_symbol text NOT NULL,
  "date" date NOT NULL,
  "period" mstar."statement_period" NOT NULL,
  currency text NOT NULL,
  income_loss_before_adjustment numeric NULL,
  depreciation_amortization_depletion numeric NULL,
  total_adjustments numeric NULL,
  changes_in_operating_capital numeric NULL,
  cash_generated_from_operations numeric NULL,
  taxes_refund_paid numeric NULL,
  other_operating_cash_flow numeric NULL,
  net_cash_flow_from_continuing_operations numeric NULL,
  net_cash_flow_from_discontinuing_operations numeric NULL,
  cash_flow_from_operations numeric NULL,
  purchase_sale_disposal_of_property_plant_equipment numeric NULL,
  purchase_sale_of_business numeric NULL,
  purchase_sale_of_investments numeric NULL,
  capital_expenditure_reported numeric NULL,
  other_investing_cash_flow numeric NULL,
  change_in_securities_borrowed numeric NULL,
  purchase_sale_of_intangibles numeric NULL,
  increase_decrease_in_restricted_cash_and_equivalents numeric NULL,
  payment_for_loan_granted_and_repayments_received numeric NULL,
  purchase_sale_of_equity_investments numeric NULL,
  purchase_sale_of_investment_properties numeric NULL,
  receipts_and_payments_for_loans numeric NULL,
  change_in_investing_deposits numeric NULL,
  purchase_sale_of_other_non_current_assets numeric NULL,
  exploration_and_mine_development_costs numeric NULL,
  investing_dividends_received_paid numeric NULL,
  investing_interest_received_paid numeric NULL,
  cash_flow_from_continuing_investments numeric NULL,
  net_cash_flow_from_discontinuing_investments numeric NULL,
  cash_flow_from_investments numeric NULL,
  issuance_of_payments_for_common_stock numeric NULL,
  issuance_of_repayments_for_short_term_debt numeric NULL,
  issuance_of_repayments_for_long_term_debt numeric NULL,
  issuance_of_repayments_for_debt numeric NULL,
  issuance_of_payments_for_preferred_stock numeric NULL,
  other_financing_cash_flow numeric NULL,
  net_movement_in_minority_interest numeric NULL,
  change_in_securities_loaned numeric NULL,
  proceeds_from_issuance_exercising_of_stock_options_warrants numeric NULL,
  excess_tax_benefit_from_share_based_compensation numeric NULL,
  change_in_policyholder_funds_and_contracts numeric NULL,
  issuance_of_repayments_for_partners_equity numeric NULL,
  cash_dividends_and_interest_paid numeric NULL,
  issuance_of_repayments_for_lease_financing numeric NULL,
  issue_and_financing_costs numeric NULL,
  cash_dividends_paid_to_minority_interests numeric NULL,
  cash_flow_from_continuing_financing numeric NULL,
  net_cash_flow_from_discontinuing_financing numeric NULL,
  cash_flow_from_financing numeric NULL,
  change_in_cash numeric NULL,
  effect_of_exchange_rates numeric NULL,
  cash_and_equivalents_beginning_of_period numeric NULL,
  cash_and_equivalents_end_of_period numeric NULL,
  CONSTRAINT cash_flow_statement_pkey PRIMARY KEY (act_symbol, date, period),
  CONSTRAINT cash_flow_statement_act_symbol_fkey FOREIGN KEY (act_symbol) REFERENCES nasdaq.symbol(act_symbol)
);

CREATE TABLE mstar.income_statement (
  act_symbol text NOT NULL,
  "date" date NOT NULL,
  "period" mstar."statement_period" NOT NULL,
  currency text NOT NULL,
  total_revenue numeric NULL,
  cost_of_revenue numeric NULL,
  gross_profit numeric NULL,
  total_expenses numeric NULL,
  selling_general_administrative_expenses numeric NULL,
  operating_income_expenses numeric NULL,
  total_operating_profit_loss numeric NULL,
  total_net_finance_income_expenses numeric NULL,
  irregular_income_expenses numeric NULL,
  other_non_operating_income_expenses numeric NULL,
  total_non_operating_income_expenses numeric NULL,
  pretax_income numeric NULL,
  provision_for_income_tax numeric NULL,
  earnings_from_equity_interest numeric NULL,
  net_income_before_extraordinary_items_and_discontinued_operatio numeric NULL,
  discontinued_operations numeric NULL,
  extraordinary_items numeric NULL,
  other_net_of_taxes_adjustments numeric NULL,
  net_income_after_extraordinary_items_and_discontinued_operation numeric NULL,
  minority_interests numeric NULL,
  net_income_after_minority_interests numeric NULL,
  preferred_other_stock_distribution numeric NULL,
  other_adjustments_to_net_income numeric NULL,
  net_income numeric NULL,
  dilution_to_earnings numeric NULL,
  diluted_net_income numeric NULL,
  net_income_allocated_to_common_unitholders numeric NULL,
  total_gross_dividends numeric NULL,
  comprehensive_income numeric NULL,
  basic_eps numeric NULL,
  basic_average_shares numeric NULL,
  diluted_eps numeric NULL,
  diluted_average_shares numeric NULL,
  preferred_dividend_per_share numeric NULL,
  total_dividend_per_share numeric NULL,
  CONSTRAINT income_statement_pkey PRIMARY KEY (act_symbol, date, period),
  CONSTRAINT income_statement_act_symbol_fkey FOREIGN KEY (act_symbol) REFERENCES nasdaq.symbol(act_symbol)
);

CREATE TABLE mstar.symbol (
  act_symbol text NOT NULL,
  "exchange" text NOT NULL,
  morningstar_id text NOT NULL,
  CONSTRAINT symbol_pkey PRIMARY KEY (morningstar_id)
);
